default:
  tags:
    - dcthra

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm api_gateway_service python -m unittest discover test_api_gateway_service.py

deploy:
  stage: deploy
  script:
    - docker-compose up -d