version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    networks:
      - mynetwork
  service1:
    build:
      context: ./service1
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
  service2:
    build:
      context: ./service2
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
  monitoring_service:
    build:
      context: ./monitoring_service
    depends_on:
      - rabbitmq
    ports:
      - "8087:8087"
    networks:
      - mynetwork
networks:
  mynetwork:
