version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    networks:
      - mynetwork
  service1:
    build:
      context: ./service1
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
  service2:
    build:
      context: ./service2
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
  monitoring_service:
    build:
      context: ./monitoring_service
    depends_on:
      - rabbitmq
    networks:
      - mynetwork
  api_gateway_service:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./api_gateway_service
    depends_on:
      - rabbitmq
    ports:
      - "8083:8083"
    networks:
      - mynetwork
networks:
  mynetwork:
