version: '3'

services:
  service1:
    build:
      context: ./service1
    volumes:
      - ./logs:/logs
    networks:
      - localnetwork

  service2:
    build:
      context: ./service2
    volumes:
      - ./logs:/logs
    networks:
      - localnetwork

networks:
  localnetwork:
